name       : engauge-digitizer
version    : 12.1
release    : 10
source     :
    - https://github.com/markummitchell/engauge-digitizer/archive/v12.1.tar.gz : b553c71ad8b5565a42ae0ba58891d27ac47ca27cc6d7a442c979b56b1fbda282
license    : GPL-2.0-or-later
component  : office.scientific
summary    : Extracts data points from images of graphs
description: |
    The Engauge Digitizer tool accepts image files (like PNG, JPEG and TIFF) containing graphs, and recovers the data points from those graphs. The resulting data points are usually used as input to other software applications. Conceptually, Engauge Digitizer is the opposite of a graphing tool that converts data points to graphs.
builddeps  :
    - pkgconfig(fftw3)
    - pkgconfig(libjpeg)
    - pkgconfig(libopenjp2)
    - pkgconfig(libpng)
    - pkgconfig(log4cpp)
    - pkgconfig(poppler-qt5)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5Designer)
setup      : |
    export OPENJPEG_INCLUDE=$(pkg-config --cflags-only-I libopenjp2 | sed -e 's@-I\(\S\+\).*@\1@g')
    export OPENJPEG_LIB=%libdir%
    export POPPLER_INCLUDE=$(pkg-config --cflags-only-I poppler-qt5 | sed -e 's@-I\(\S\+\).*@\1@g')
    export POPPLER_LIB=%libdir%

    %qmake engauge.pro CONFIG+="jpeg2000 pdf" DEFINES+="HELPDIR=/usr/share/engauge-digitizer/doc"
build      : |
    %make
    lrelease engauge.pro
    $workdir/help/build.bash
install    : |
    install -Dm00755 $workdir/bin/engauge $installdir/usr/bin/engauge

    install -Dm00644 $workdir/src/img/bannerapp_64.xpm $installdir/usr/share/pixmaps/engauge-digitizer.xpm
    install -Dm00644 $workdir/dev/engauge-digitizer.desktop $installdir/usr/share/applications/engauge-digitizer.desktop

    install -Dm00644 -t $installdir/usr/share/engauge-digitizer/translations $workdir/translations/*.qm
    install -Dm00644 -t $installdir/usr/share/engauge-digitizer/doc $workdir/bin/documentation/*
