name       : engauge-digitizer
version    : 10.12
release    : 3
source     :
    - https://github.com/markummitchell/engauge-digitizer/archive/v10.12.tar.gz : 2f6358e58bd1517b39d021b543dbd34909e56e42b336935dd74d0a23fac2c975
license    : GPL-2.0-or-later
component  : office.scientific
summary    : Extracts data points from images of graphs
description: "The Engauge Digitizer tool accepts image files (like PNG, JPEG and TIFF) containing graphs, and \nrecovers the data points from those graphs. The resulting data points are usually used as\
    \ input\nto other software applications. Conceptually, Engauge Digitizer is the opposite of a graphing\ntool that converts data points to graphs.\n"
builddeps  :
    - pkgconfig(fftw3)
    - pkgconfig(libjpeg)
    - pkgconfig(libopenjp2)
    - pkgconfig(libpng)
    - pkgconfig(log4cpp)
    - pkgconfig(poppler-qt5)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5Designer)
setup      : |
    export OPENJPEG_INCLUDE=$(pkg-config --cflags-only-I libopenjp2 | sed -e 's@-I\(\S\+\).*@\1@g')
    export OPENJPEG_LIB=%libdir%
    export POPPLER_INCLUDE=$(pkg-config --cflags-only-I poppler-qt5 | sed -e 's@-I\(\S\+\).*@\1@g')
    export POPPLER_LIB=%libdir%

    %qmake engauge.pro CONFIG+="jpeg2000 pdf" DEFINES+="HELPDIR=/usr/share/engauge-digitizer/doc"
build      : |
    %make
    lrelease engauge.pro
    $workdir/help/build.bash
install    : |
    install -Dm00755 $workdir/bin/engauge $installdir/usr/bin/engauge

    install -Dm00644 $workdir/src/img/bannerapp_64.xpm $installdir/usr/share/pixmaps/engauge-digitizer.xpm
    install -Dm00644 $pkgfiles/engauge-digitizer.desktop $installdir/usr/share/applications/engauge-digitizer.desktop

    install -Dm00644 -t $installdir/usr/share/engauge-digitizer/translations $workdir/translations/*.qm
    install -Dm00644 -t $installdir/usr/share/engauge-digitizer/doc $workdir/bin/documentation/*
